---
title: "plotly"
author: "jjw"
date: "19 January 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basic Scatterplot
mode="markers"" below specifies scatterplot

```{r, eval=FALSE}
library(plotly)
plot_ly(mtcars, x = mtcars$wt, y = mpg, mode = "markers")
```

## Scatterplot Colour

```{r , echo=FALSE, message=FALSE}
plot_ly(x = mtcars$wt, y = mtcars$mpg, mode = "markers", color = as.factor(mtcars$cyl))
```

## Continuous Colour
Colour using a continuous variable

```{r , echo=FALSE, message=FALSE}
plot_ly(x = mtcars$wt, y = mtcars$mpg, mode = "markers", color = mtcars$disp)
```

## Scatterplot sizing
using size argument

```{r , echo=FALSE, message=FALSE}
plot_ly(x = mtcars$wt, y = mtcars$mpg, mode = "markers", 
        color = as.factor(mtcars$cyl), size = mtcars$hp)
```

## 3D Scatterplot


```{r , eval=FALSE}
set.seed(2016-07-21)
temp <- rnorm(100, mean = 30, sd = 5)
pressure <- rnorm(100)
dtime <- 1:100
plot_ly(x = temp, y = pressure, z = dtime,
        type = "scatter3d", mode = "markers", color = temp)

```

## Line Graph


```{r , eval=FALSE, message=FALSE}
data("airmiles")
plot_ly(x = time(airmiles), y=airmiles, mode="lines")

```

## Multiline Graph
The default graph.  Dont need mode= or type=


```{r , eval=FALSE, message=FALSE}
library(plotly)
library(tidyr)
library(dplyr)
data("EuStockMarkets")

stocks <- as.data.frame(EuStockMarkets) %>% 
  gather(index, price) %>% 
  mutate(time= rep(time(EuStockMarkets), 4))


plot_ly(stocks, x = stocks$time, y=stocks$price, color = stocks$index, mode="lines")

```

## Histogram

```{r , eval=FALSE, message=FALSE}
plot_ly(x = precip, type="histogram")

```

## boxplot
```{r , eval=FALSE, message=FALSE}
plot_ly(y = iris$Petal.Length, color=iris$Species type="box")

```
## heatmap
```{r , eval=FALSE, message=FALSE}
terrain1 <- matrix(rnorm(100*100), nrow=100, ncol=100)
plot_ly(z=terrain1, type="heatmap")

```

## 3D Surface
```{r , eval=FALSE, message=FALSE}
terrain2 <- matrix(sort(rnorm(100*100)), nrow=100, ncol=100)
plot_ly(z=terrain2, type="surface")

```

## Maps
```{r , eval=FALSE, message=FALSE}
# Create data frame
state_pop <- data.frame(State = state.abb, Pop = as.vector(state.x77[,1]))
# Create hover text
state_pop$hover <- with(state_pop, paste(State, '<br>', "Population:", Pop))
# make state borders red
borders <- list(color = toRGB("red"))
# Set up some mapping options
map_options <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

plot_ly(z=state_pop$Pop, text = state_pop$hover, locations = state_pop$State,
        type = 'choropleth', locationmode = 'USA-states',
        color = state_pop$Pop, colors = 'Blues', marker = list(line = borders)) %>% 
  layout(title = 'US Population in 1975', geo=map_options)

```

## ggplot in plotly
```{r , eval=FALSE, message=FALSE}
set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000),]
p <- ggplot(data = d, aes(x = carat, y = price)) +
  geom_point(aes(text = paste("Clarity:", clarity)), size = 4) +
  geom_smooth(aes(colour = cut, fill = cut)) + facet_wrap(~ cut)

(gg <- ggplotly(p))

```