---
title: "googleVis"
author: "jjw"
date: "18/01/2021"
output: html_document
---

* The R function creates an HTML page
* The HTML page calls Google Charts
* The result is an interactive HTML graphic



## Example
## Chart
```{r gv, results="asis", cache=TRUE}

suppressPackageStartupMessages(library(googleVis))
G <- gvisGeoChart(Exports, locationvar="Country",
                  colorvar="Profit", options=list(width=600, height=400))
#print(G, "chart")


```

## Charts in googleVis



```{r chart2, dependson="gv", results="asis", cache=TRUE}
G2 <- gvisGeoChart(Exports, locationvar="Country",
                  colorvar="Profit", options=list(width=600, height=400, region = "150"))
```

## Line chart

```{r linie, dependson="gv", results="asis", cache=TRUE}
df <- data.frame(label=c("US", "GB", "BR"), val1=c(1,3,4), val2=c(23,12,32))
Line <- gvisLineChart(df, xvar="label", yvar=c("val1", "val2"),
                      options=list(title="Hello World", legend="bottom",
                                   titleTextStyle="{color:'red', fontSize:18)",
                                   vAxis="{gridlines:{color:'red', count:3}}",
                                   hAxis="{title:'My Label', titleTextStyle:{color:'blue'}}",
                                   series="[{title:'Value 1 (%)', format:'##, ######%'}]",
                                   curveType="function", width=500, height=300
                      ))
                 
```

## Joining multiple plots
```{r multi, dependson="gv", results="asis", cache=TRUE}
G <- gvisGeoChart(Exports, "Country", "Profit", options=list(width=200, height=100))
T1 <- gvisTable(Exports, options=list(width=200, height=270))
M <- gvisMotionChart(Fruits, "Fruit", "Year", options=list(width=400, height=370))
GT <- gvisMerge(G,T1, horizontal=FALSE)
GTM <- gvisMerge(GT, M, horizontal=TRUE, tableOptions="bgcolor=\"#CCCCCC\" cellspacing=10")
                 
```

## Seeing the HTML code

